smnc_.smc.hip_link_length = 0.055;
smnc_.smc.upper_leg_link_length = 0.1075;
smnc_.smc.lower_leg_link_length = 0.130;
smnc_.smc.body_width = 0.078;
smnc_.smc.body_length = 0.186;
smnc_.default_stand_height = 0.155;
smnc_.stand_front_x_offset = 0.015;
smnc_.stand_back_x_offset = -0.000;
smnc_.lie_down_height = 0.083;
smnc_.lie_down_feet_x_offset = 0.065;
smnc_.num_servos = 12;
smnc_.servo_max_angle_deg = 82.5;
smnc_.transit_tau = 0.3;
smnc_.transit_rl = 0.06;
smnc_.transit_angle_rl = 0.35;
smnc_.max_fwd_velocity = 0.4;
smnc_.max_side_velocity = 0.4;
smnc_.max_yaw_rate = 0.35;
smnc_.z_clearance = 0.050;
smnc_.alpha = 0.5;
smnc_.beta = 0.5;
smnc_.foot_height_time_constant = 0.02;
smnc_.num_phases = 8;
smnc_.overlap_time = 0.0;
smnc_.swing_time = 0.36;
smnc_.fwd_body_balance_shift = 0.035;
smnc_.back_body_balance_shift = 0.005;
smnc_.side_body_balance_shift = 0.015;
smnc_.lidar_x_pos = 0.045;
smnc_.lidar_y_pos = 0.0;
smnc_.lidar_z_pos = 0.085;
smnc_.lidar_yaw_angle = 180;
smnc_.dt = 0.02;
smnc_.publish_odom = true;
smnc_.debug_mode = false;
smnc_.plot_mode = false;
smnc_.servo_config["RF_3"] = {{"num", 1},  {"center", 345}, {"range", 320}, {"direction",  1},  {"center_angle_deg",  88.2}};
smnc_.servo_config["RF_2"] = {{"num", 2},  {"center", 258}, {"range", 320}, {"direction",  1},  {"center_angle_deg", -27.6}};
smnc_.servo_config["RF_1"] = {{"num", 3},  {"center", 282}, {"range", 320}, {"direction", -1},  {"center_angle_deg",  -5.4}};
smnc_.servo_config["RB_3"] = {{"num", 4},  {"center", 360}, {"range", 320}, {"direction",  1},  {"center_angle_deg",  85.8}};
smnc_.servo_config["RB_2"] = {{"num", 5},  {"center", 270}, {"range", 320}, {"direction",  1},  {"center_angle_deg", -35.4}};
smnc_.servo_config["RB_1"] = {{"num", 6},  {"center", 321}, {"range", 320}, {"direction",  1},  {"center_angle_deg",  -4.4}};
smnc_.servo_config["LB_3"] = {{"num", 7},  {"center", 273}, {"range", 320}, {"direction",  1},  {"center_angle_deg", -73.9}};
smnc_.servo_config["LB_2"] = {{"num", 8},  {"center", 291}, {"range", 320}, {"direction",  1},  {"center_angle_deg",  38.7}};
smnc_.servo_config["LB_1"] = {{"num", 9},  {"center", 309}, {"range", 320}, {"direction", -1},  {"center_angle_deg",  -0.4}};
smnc_.servo_config["LF_3"] = {{"num", 10}, {"center", 282}, {"range", 320}, {"direction",  1},  {"center_angle_deg", -82.8}};
smnc_.servo_config["LF_2"] = {{"num", 11}, {"center", 321}, {"range", 320}, {"direction",  1},  {"center_angle_deg",  38.6}};
smnc_.servo_config["LF_1"] = {{"num", 12}, {"center", 291}, {"range", 320}, {"direction",  1},  {"center_angle_deg",  -7.6}};
smnc_.rb_contact_phases.push_back(1);
smnc_.rb_contact_phases.push_back(0);
smnc_.rb_contact_phases.push_back(1);
smnc_.rb_contact_phases.push_back(1);
smnc_.rb_contact_phases.push_back(1);
smnc_.rb_contact_phases.push_back(1);
smnc_.rb_contact_phases.push_back(1);
smnc_.rb_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(0);
smnc_.rf_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(1);
smnc_.rf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(1);
smnc_.lf_contact_phases.push_back(0);
smnc_.lb_contact_phases.push_back(1);
smnc_.lb_contact_phases.push_back(1);
smnc_.lb_contact_phases.push_back(1);
smnc_.lb_contact_phases.push_back(1);
smnc_.lb_contact_phases.push_back(1);
smnc_.lb_contact_phases.push_back(0);
smnc_.lb_contact_phases.push_back(1);
smnc_.lb_contact_phases.push_back(1);
smnc_.body_shift_phases.push_back(1);
smnc_.body_shift_phases.push_back(2);
smnc_.body_shift_phases.push_back(3);
smnc_.body_shift_phases.push_back(4);
smnc_.body_shift_phases.push_back(5);
smnc_.body_shift_phases.push_back(6);
smnc_.body_shift_phases.push_back(7);
smnc_.body_shift_phases.push_back(8);
